
-- Concepts

    # event-time
        + Example
            - The time a geo-location change is reported by GPS sensor

    # processing-time
        +  Example
            - The time an application reads & process this geo-location
              for consumption by some dashboard

    # ingestion-time
        + The time when the event or record is stored in kafka topic
        + This time is generated by kafka broker when the
          record is appended to kafka topic by the broker

-- In Kafka Stream

    # Timestamps
        + Timestamp extractors
            - Kafka stream assigns timestamp to every record via the
              timestamp extractors
            - https://docs.confluent.io/current/streams/concepts.html#timestamps
        + Describes the progress of stream with regards to time
        + Joins
            + Is leveraged by time dependent operation such as joins
        + Also called as event-time

    # Reference
        https://docs.confluent.io/current/streams/concepts.html#time

-- Best Practice

    # Agree on specific timezones for all the topics
    # https://docs.confluent.io/current/streams/concepts.html#other-aspects-of-time